version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
